In [43]:
#importing the required dependencies 
import numpy as np
import pandas as pd

In [44]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [68]:
#UPLOADING THE CSV FILE USING PANDAS. 
df = pd.read_csv(r"C:\Users\ACER\Anaconda3\envs\Cars\carrs.csv")


In [5]:
df.head(3)

Make           Model   Type Origin DriveTrain     MSRP  Invoice  \
0  Acura             MDX    SUV   Asia        All  $36,945  $33,337   
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  $23,820  $21,761   
2  Acura         TSX 4dr  Sedan   Asia      Front  $26,990  $24,647   

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0         265        17           23    4451   
1         2.0        4.0         200        24           31    2778   
2         2.4        4.0         200        22           29    3230   

   Wheelbase  Length  
0        106     189  
1        101     172  
2        105     183

In [6]:
#RETURNS THE SHAPE OF THE FILE
df.shape

(428, 15)

In [38]:
columns = ['Make','Model','MSRP']
df[columns].head(5)

Make           Model     MSRP
0  Acura             MDX  $36,945
1  Acura  RSX Type S 2dr  $23,820
2  Acura         TSX 4dr  $26,990
3  Acura          TL 4dr  $33,195
4  Acura      3.5 RL 4dr  $43,755

In [8]:
#USES AN EMPTY LIST AND ADDS REQUIRED DATA AFTER INSTRUCTION
def get_important_features(data):
    important_features = []
    for i in range(0,data.shape[0]):
        important_features.append(data['Make'][i]+''+data['Model'][i]+''+data['Type'][i]+''+data['Origin'][i])
    
    return important_features
       

In [9]:
df['important_features'] = get_important_features(df)
df.head(3)

Make           Model   Type Origin DriveTrain     MSRP  Invoice  \
0  Acura             MDX    SUV   Asia        All  $36,945  $33,337   
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  $23,820  $21,761   
2  Acura         TSX 4dr  Sedan   Asia      Front  $26,990  $24,647   

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0         265        17           23    4451   
1         2.0        4.0         200        24           31    2778   
2         2.4        4.0         200        22           29    3230   

   Wheelbase  Length            important_features  
0        106     189               AcuraMDXSUVAsia  
1        101     172  AcuraRSX Type S 2drSedanAsia  
2        105     183         AcuraTSX 4drSedanAsia

In [10]:
#IT CONVERS THE GIVEN DATA IN THE FORM OF MATRIX 
cm = CountVectorizer().fit_transform(df['important_features'])

In [11]:
# COSINE SIMILARITY COMPUTES SIMILARITY AS A NORMALIZED DOT PRODUCT OF X AND Y
cs = cosine_similarity(cm)
print(cs)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [12]:
cs.shape

(428, 428)

In [13]:
# IT CHECKS IF THERE ARE ANY VALUES THAT ARE NULL
df[columns].isnull().values.any()

False

In [19]:

table = df
user_type = input("Enter the Type of car you would like : ")
table = table[table.Type == user_type]
table.head(10)

Enter the Type of car you would like : Sedan


Make                      Model   Type  Origin DriveTrain     MSRP  \
1   Acura             RSX Type S 2dr  Sedan    Asia      Front  $23,820   
2   Acura                    TSX 4dr  Sedan    Asia      Front  $26,990   
3   Acura                     TL 4dr  Sedan    Asia      Front  $33,195   
4   Acura                 3.5 RL 4dr  Sedan    Asia      Front  $43,755   
5   Acura    3.5 RL w/Navigation 4dr  Sedan    Asia      Front  $46,100   
7    Audi                A4 1.8T 4dr  Sedan  Europe      Front  $25,940   
8    Audi     A41.8T convertible 2dr  Sedan  Europe      Front  $35,940   
9    Audi                 A4 3.0 4dr  Sedan  Europe      Front  $31,840   
10   Audi  A4 3.0 Quattro 4dr manual  Sedan  Europe        All  $33,430   
11   Audi    A4 3.0 Quattro 4dr auto  Sedan  Europe        All  $34,480   

    Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
1   $21,761         2.0        4.0         200        24           31    2778   
2   $24,647         2.4        4.0         200        22           29    3230   
3   $30,299         3.2        6.0         270        20           28    3575   
4   $39,014         3.5        6.0         225        18           24    3880   
5   $41,100         3.5        6.0         225        18           24    3893   
7   $23,508         1.8        4.0         170        22           31    3252   
8   $32,506         1.8        4.0         170        23           30    3638   
9   $28,846         3.0        6.0         220        20           28    3462   
10  $30,366         3.0        6.0         220        17           26    3583   
11  $31,388         3.0        6.0         220        18           25    3627   

    Wheelbase  Length                        important_features  
1         101     172              AcuraRSX Type S 2drSedanAsia  
2         105     183                     AcuraTSX 4drSedanAsia  
3         108     186                      AcuraTL 4drSedanAsia  
4         115     197                  Acura3.5 RL 4drSedanAsia  
5         115     197     Acura3.5 RL w/Navigation 4drSedanAsia  
7         104     179                AudiA4 1.8T 4drSedanEurope  
8         105     180     AudiA41.8T convertible 2drSedanEurope  
9         104     179                 AudiA4 3.0 4drSedanEurope  
10        104     179  AudiA4 3.0 Quattro 4dr manualSedanEurope  
11        104     179    AudiA4 3.0 Quattro 4dr autoSedanEurope

In [20]:
user_Make = input("Enter the preffered company : ")
table = table[table.Make == user_Make]
table.head(10)

Enter the preffered company : Audi


Make                           Model   Type  Origin DriveTrain     MSRP  \
7   Audi                     A4 1.8T 4dr  Sedan  Europe      Front  $25,940   
8   Audi          A41.8T convertible 2dr  Sedan  Europe      Front  $35,940   
9   Audi                      A4 3.0 4dr  Sedan  Europe      Front  $31,840   
10  Audi       A4 3.0 Quattro 4dr manual  Sedan  Europe        All  $33,430   
11  Audi         A4 3.0 Quattro 4dr auto  Sedan  Europe        All  $34,480   
12  Audi                      A6 3.0 4dr  Sedan  Europe      Front  $36,640   
13  Audi              A6 3.0 Quattro 4dr  Sedan  Europe        All  $39,640   
14  Audi          A4 3.0 convertible 2dr  Sedan  Europe      Front  $42,490   
15  Audi  A4 3.0 Quattro convertible 2dr  Sedan  Europe        All  $44,240   
16  Audi        A6 2.7 Turbo Quattro 4dr  Sedan  Europe        All  $42,840   

    Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
7   $23,508         1.8        4.0         170        22           31    3252   
8   $32,506         1.8        4.0         170        23           30    3638   
9   $28,846         3.0        6.0         220        20           28    3462   
10  $30,366         3.0        6.0         220        17           26    3583   
11  $31,388         3.0        6.0         220        18           25    3627   
12  $33,129         3.0        6.0         220        20           27    3561   
13  $35,992         3.0        6.0         220        18           25    3880   
14  $38,325         3.0        6.0         220        20           27    3814   
15  $40,075         3.0        6.0         220        18           25    4013   
16  $38,840         2.7        6.0         250        18           25    3836   

    Wheelbase  Length                             important_features  
7         104     179                     AudiA4 1.8T 4drSedanEurope  
8         105     180          AudiA41.8T convertible 2drSedanEurope  
9         104     179                      AudiA4 3.0 4drSedanEurope  
10        104     179       AudiA4 3.0 Quattro 4dr manualSedanEurope  
11        104     179         AudiA4 3.0 Quattro 4dr autoSedanEurope  
12        109     192                      AudiA6 3.0 4drSedanEurope  
13        109     192              AudiA6 3.0 Quattro 4drSedanEurope  
14        105     180          AudiA4 3.0 convertible 2drSedanEurope  
15        105     180  AudiA4 3.0 Quattro convertible 2drSedanEurope  
16        109     192        AudiA6 2.7 Turbo Quattro 4drSedanEurope

In [22]:
user_hp = input("Enter the minimum horsepower : ")
table = table[table.Horsepower > int(user_hp)]
table.head()

Enter the minimum horsepower : 225


Make                     Model   Type  Origin DriveTrain     MSRP  \
16  Audi  A6 2.7 Turbo Quattro 4dr  Sedan  Europe        All  $42,840   
17  Audi        A6 4.2 Quattro 4dr  Sedan  Europe        All  $49,690   
18  Audi          A8 L Quattro 4dr  Sedan  Europe        All  $69,190   
19  Audi            S4 Quattro 4dr  Sedan  Europe        All  $48,040   

    Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
16  $38,840         2.7        6.0         250        18           25    3836   
17  $44,936         4.2        8.0         300        17           24    4024   
18  $64,740         4.2        8.0         330        17           24    4399   
19  $43,556         4.2        8.0         340        14           20    3825   

    Wheelbase  Length                       important_features  
16        109     192  AudiA6 2.7 Turbo Quattro 4drSedanEurope  
17        109     193        AudiA6 4.2 Quattro 4drSedanEurope  
18        121     204          AudiA8 L Quattro 4drSedanEurope  
19        104     179            AudiS4 Quattro 4drSedanEurope

In [39]:
table = table[columns]


In [47]:
print("The favorable cars according to your choices are.....  ")

The favorable cars according to your choices are.....  


In [64]:
#THIS SHOWS THE FINAL RECOMMENDATIONS BASED ON THE USER'S CHOICE 
table.head()

Make                     Model     MSRP
16  Audi  A6 2.7 Turbo Quattro 4dr  $42,840
17  Audi        A6 4.2 Quattro 4dr  $49,690
18  Audi          A8 L Quattro 4dr  $69,190
19  Audi            S4 Quattro 4dr  $48,040